name: Check User Schedules

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API to check schedules
        run: |
          curl --retry 5 --retry-delay 5 \
          -H "X-Admin-Key: ${{ secrets.ADMIN_API_KEY }}" \
          https://personal-assistant-8occ.onrender.com/check-schedules

      - name: Call API to check email syncs
        run: |
          curl --retry 5 --retry-delay 5 \
          -H "X-Admin-Key: ${{ secrets.ADMIN_API_KEY }}" \
          https://personal-assistant-8occ.onrender.com/check-email-sync
