name: Run Daily Schedule

on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render API
        run: curl https://personal-assistant-8occ.onrender.com/run-daily-schedule
