name: Check User Schedules

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API to check schedules
        run: curl https://personal-assistant-8occ.onrender.com/api/system/check-schedules
